### ISSUE TITLE
ValueError: The two structures don't have the same nested structure.

### ISSUE THREAD

**Issue by DrDairiAek** [abhilash1910/SpectralEmbeddings#2]
Hi, first of all, thanks for your share, i'm facing a problem when running the test.py, with train.csv as suggested (from Kaggel), my Keras version is 2.3.1 and Tensorflow 2.1 : 
ValueError: The two structures don't have the same nested structure.
First structure: type=SparseTensorSpec str=SparseTensorSpec(TensorShape([39, 39]), tf.float64)

Second structure: type=SparseTensor str=SparseTensor(indices=Tensor("first/indices:0", shape=(None, 2), dtype=int64), values=Tensor("first/values:0", shape=(None,), dtype=float32), dense_shape=Tensor("first/shape:0", shape=(2,), dtype=int64))

More specifically: Incompatible CompositeTensor TypeSpecs: type=SparseTensorSpec str=SparseTensorSpec(TensorShape([39, 39]), tf.float64) vs. type=SparseTensorSpec str=SparseTensorSpec(TensorShape([None, None]), tf.float32)

Thanks again

**Comment by abhilash1910** [comment]
Hi @kadirou31 , could you please tell the following points?
- Are you using the same codebase which is there in [test.py](https://github.com/abhilash1910/SpectralEmbeddings/blob/master/test.py)
-  I am seeing that you have placed the subset value as 39 ? Could you please share a demo colab notebook so that I can look into it
Thanks

**Comment by DrDairiAek** [comment]
Hi
Thank you for your fast reply, I upgraded my tensorflow and keras to 2.6
it's OK now.
However I noticed that X used for training do not comes from train.csv it
is based on arange function. My concern is about shaping the dataset to
meet GCN requirements.
Thanks again for your help.

**Comment by abhilash1910** [comment]
Hi,
Yes the X is from a np.arange method call. Here we are directly passing the node points as feature vectors ; Also for using this framework (for GCN kernels) only specifying the number of sequences to generate the embedding spaces are requried.
For instance in a csv having 'labels' and 'text' columns , out of 1000 input entries, if I would want to generate a KG with 567 nodes, I would have to specify that in the subset arguement. This will also pickup the labels associated with those 567 nodes; if the labels are less in number then an automatic sampling of the labels for the nodes are generated. 
You can refer to any textual dataset having 2 major columns (the text and the labels) and apply this approach (from test.py or from the kaggle/Colab notebook). 
Hope this helps. If the issue is resolved please feel free to close it ; and if you have doubts I will try to create a new sample example to elucidate.
Thanks
Best,
Abhilash

**Comment by DrDairiAek** [comment]
Hi,
many thanks for your quick replay
